name: Update HTML files

on:
  pull_request:
    paths:
      - "problems.yaml"

jobs:
  generate_html:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          persist-credentials: true
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.10"
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Generate html
        run: uv run yaml_to_html.py
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: Auto-update HTML files"
